import {
  AlertTriangle,
  Building2,
  Calendar,
  Car,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileText,
  FolderTree,
  IndianRupee,
  LayoutDashboard,
  MapPin,
  PiggyBank,
  Receipt,
  RefreshCw,
  Settings,
  Tag,
  Timer,
  UserPlus,
  Users,
  Wallet,
} from "lucide-react";

export const adminSidebarMenu = [
  {
    type: "section",
    title: "Main Menu",
    permissionKey: "main",
    items: [
      {
        type: "link",
        label: "Dashboard",
        icon: LayoutDashboard,
        path: "/admin/dashboard",
        permissionKey: "dashboard",
      },
    ],
  },
  {
    type: "section",
    title: "Vendors",
    permissionKey: "vendors",
    items: [
      {
        type: "link",
        label: "Vendor List",
        icon: Building2,
        path: "/admin/vendors",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Joining Requests",
        icon: UserPlus,
        path: "/admin/joining-requests",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Category Approvals",
        icon: FolderTree,
        path: "/admin/category-approvals",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "EV Approvals",
        icon: Car,
        path: "/admin/ev-approvals",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Coupon Approvals",
        icon: Tag,
        path: "/admin/coupon-approvals",
        permissionKey: "joining_requests",
      },
      {
        type: "link",
        label: "Vendor Withdrawals",
        icon: Wallet,
        path: "/admin/vendor-withdrawals",
        permissionKey: "joining_requests",
      },
    ],
  },
  {
    type: "section",
    title: "Inventory",
    permissionKey: "inventory",
    items: [
      {
        type: "link",
        label: "EV Rent Zones",
        icon: MapPin,
        path: "/admin/zones",
        permissionKey: "zones",
      },
      {
        type: "link",
        label: "EV Categories",
        icon: FolderTree,
        path: "/admin/categories",
        permissionKey: "categories",
      },
      {
        type: "link",
        label: "EV Management",
        icon: Car,
        path: "/admin/evs",
        permissionKey: "bikes",
      },
    ],
  },
  {
    type: "section",
    title: "Bookings",
    permissionKey: "bookings",
    items: [
      {
        type: "link",
        label: "Live Rentals",
        icon: Car,
        path: "/admin/bookings?ops=live",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Upcoming Pickups",
        icon: Clock,
        path: "/admin/bookings?ops=pickups",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Upcoming Returns",
        icon: RefreshCw,
        path: "/admin/bookings?ops=returns",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Late Returns",
        icon: AlertTriangle,
        path: "/admin/bookings?ops=late",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Extension Requests",
        icon: Timer,
        path: "/admin/bookings?ops=extensions",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Pending Deposits",
        icon: PiggyBank,
        path: "/admin/bookings?depositStatus=pending_collection",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Pending Approvals",
        icon: Clock,
        path: "/admin/bookings?status=pending_approval",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "Fleet Timeline",
        icon: Calendar,
        path: "/admin/fleet-timeline",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "EV Inspections",
        icon: ClipboardCheck,
        path: "/admin/inspections",
        permissionKey: "list",
      },
      {
        type: "link",
        label: "All Bookings",
        icon: ClipboardList,
        path: "/admin/bookings",
        permissionKey: "list",
      },
    ],
  },
  {
    type: "section",
    title: "Customers",
    permissionKey: "customers",
    items: [
      {
        type: "link",
        label: "Customers",
        icon: Users,
        path: "/admin/customers",
        permissionKey: "list",
      },
    ],
  },
  {
    type: "section",
    title: "Operations",
    permissionKey: "operations",
    items: [
      {
        type: "link",
        label: "Reports",
        icon: FileText,
        path: "/admin/reports",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Wallet & Refunds",
        icon: Wallet,
        path: "/admin/wallet",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Coupons",
        icon: Tag,
        path: "/admin/coupons",
        permissionKey: "coupons",
      },
      {
        type: "link",
        label: "Finance",
        icon: PiggyBank,
        path: "/admin/finance",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Settlements",
        icon: IndianRupee,
        path: "/admin/settlements",
        permissionKey: "reports",
      },
      {
        type: "link",
        label: "Tax & Billing",
        icon: Receipt,
        path: "/admin/tax-billing",
        permissionKey: "settings",
      },
      {
        type: "link",
        label: "Settings",
        icon: Settings,
        path: "/admin/settings",
        permissionKey: "settings",
      },
    ],
  },
];
